[build]
rustflags=[
    "-Clink-arg=-Wl,--allow-shlib-undefined",
]

[env]
# 使用python版本编译好的libtorch
LIBTORCH_USE_PYTORCH="1"
# 跳过版本检查,容器中安装的是pytorch 2.0.1的版本
LIBTORCH_BYPASS_VERSION_CHECK="1"
# 使用静态链接
LIBTORCH_STATIC="1"

[source.crates-io]
replace-with='rsproxy-sparse'
[source.rsproxy]
registry="https://rsproxy.cn/crates.io-index"
[source.rsproxy-sparse]
registry="sparse+https://rsproxy.cn/index/"
[registries.rsproxy]
index="https://rsproxy.cn/crates.io-index"
[net]
git-fetch-with-cli=true
