[build]
# 默认使用lld加快链接
rustflags=[
    "-C",
    "link-arg=-fuse-ld=lld-16",
]

# release profile下启用跨语言的lto优化
[target.'cfg(all(not(debug_assertions),target_os="linux"))']
rustflags=[
    "-C",
    "link-arg=-fuse-ld=lld-16",
    "-C",
    "linker=clang-16",
    "-C",
    "linker-plugin-lto",
]